# Generated by Django 5.2.3 on 2025-09-09 16:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shared', '0001_initial'),
        ('tenant_management', '0010_loginattempt_blacklistedtoken_passwordhistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ACCESS', 'Data Access'), ('EXPORT', 'Data Export'), ('PERMISSION_CHANGE', 'Permission Change'), ('SYSTEM_CONFIG', 'System Configuration Change'), ('SECURITY_EVENT', 'Security Event'), ('ERROR', 'Error/Exception'), ('API_CALL', 'API Call'), ('FILE_UPLOAD', 'File Upload'), ('FILE_DOWNLOAD', 'File Download')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_security_event', models.BooleanField(db_index=True, default=False)),
                ('requires_attention', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('access_type', models.CharField(choices=[('READ', 'Read'), ('SEARCH', 'Search'), ('EXPORT', 'Export'), ('REPORT', 'Report Generation'), ('BACKUP', 'Backup Access'), ('ADMIN', 'Administrative Access')], max_length=20)),
                ('data_category', models.CharField(max_length=100)),
                ('fields_accessed', models.JSONField(blank=True, default=list)),
                ('legal_basis', models.CharField(help_text='Legal basis for data processing under GDPR', max_length=100)),
                ('purpose', models.CharField(help_text='Purpose of data access', max_length=200)),
                ('request_source', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('records_accessed', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'data_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SagaStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=100)),
                ('step_order', models.IntegerField(help_text='Execution order of the step')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('compensated', 'Compensated')], default='pending', max_length=20)),
                ('input_data', models.JSONField(default=dict, help_text='Input data for the step')),
                ('output_data', models.JSONField(blank=True, help_text='Output data from the step', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('compensation_step_name', models.CharField(blank=True, help_text='Name of the compensation step to run if this step needs to be undone', max_length=100, null=True)),
                ('compensation_data', models.JSONField(blank=True, help_text='Data needed for compensation', null=True)),
            ],
            options={
                'db_table': 'saga_steps',
                'ordering': ['saga', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('FAILED_LOGIN', 'Failed Login Attempt'), ('BRUTE_FORCE', 'Brute Force Attack'), ('SUSPICIOUS_ACCESS', 'Suspicious Access Pattern'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation Attempt'), ('DATA_BREACH', 'Data Breach Incident'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('MALICIOUS_REQUEST', 'Malicious Request'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('ACCOUNT_LOCKOUT', 'Account Lockout'), ('PASSWORD_RESET', 'Password Reset'), ('PERMISSION_DENIED', 'Permission Denied'), ('CSRF_ATTACK', 'CSRF Attack Attempt'), ('XSS_ATTEMPT', 'XSS Attack Attempt'), ('SQL_INJECTION', 'SQL Injection Attempt')], max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('IGNORED', 'Ignored')], default='OPEN', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('impact_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('response_required', models.BooleanField(default=True)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('attack_vector', models.CharField(blank=True, max_length=100, null=True)),
                ('affected_resources', models.JSONField(blank=True, default=list)),
                ('remediation_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_security_events',
                'ordering': ['-audit_event__timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('change_type', models.CharField(choices=[('CONFIG', 'Configuration Change'), ('DEPLOYMENT', 'Code Deployment'), ('SECURITY_UPDATE', 'Security Update'), ('FEATURE_FLAG', 'Feature Flag Change'), ('INFRASTRUCTURE', 'Infrastructure Change'), ('DATABASE', 'Database Schema Change'), ('PERMISSION', 'Permission/Role Change'), ('INTEGRATION', 'Integration Configuration')], max_length=30)),
                ('component', models.CharField(max_length=100)),
                ('version_before', models.CharField(blank=True, max_length=50, null=True)),
                ('version_after', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('change_reason', models.TextField()),
                ('configuration_diff', models.JSONField(blank=True, null=True)),
                ('affected_services', models.JSONField(blank=True, default=list)),
                ('change_ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('downtime_minutes', models.IntegerField(default=0)),
                ('users_affected', models.IntegerField(default=0)),
                ('rollback_plan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_change_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='saga',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='saga',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saga',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saga',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saga',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='Maximum retry attempts'),
        ),
        migrations.AddField(
            model_name='saga',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Number of retries attempted'),
        ),
        migrations.AddField(
            model_name='saga',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saga',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sagas', to='tenant_management.tenantmodel'),
        ),
        migrations.AddField(
            model_name='saga',
            name='timeout_seconds',
            field=models.IntegerField(default=300, help_text='Saga timeout in seconds'),
        ),
        migrations.AlterField(
            model_name='saga',
            name='context',
            field=models.JSONField(default=dict, help_text='Saga execution context and data'),
        ),
        migrations.AlterField(
            model_name='saga',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='saga',
            name='name',
            field=models.CharField(help_text='Name of the saga type', max_length=100),
        ),
        migrations.AlterField(
            model_name='saga',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('COMPENSATING', 'Compensating')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='saga',
            index=models.Index(fields=['status', 'created_at'], name='sagas_status_381402_idx'),
        ),
        migrations.AddIndex(
            model_name='saga',
            index=models.Index(fields=['name', 'status'], name='sagas_name_a5891e_idx'),
        ),
        migrations.AddIndex(
            model_name='saga',
            index=models.Index(fields=['tenant', 'status'], name='sagas_tenant__f032f9_idx'),
        ),
        migrations.AlterModelTable(
            name='saga',
            table='sagas',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='tenant_management.tenantmodel'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='accessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataaccesslog',
            name='data_subject',
            field=models.ForeignKey(help_text='The user whose data was accessed', on_delete=django.db.models.deletion.CASCADE, related_name='data_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sagastep',
            name='saga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='shared.saga'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='audit_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_event', to='shared.auditevent'),
        ),
        migrations.AddField(
            model_name='systemchangelog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemchangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['timestamp', 'event_type'], name='audit_event_timesta_77fdab_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'timestamp'], name='audit_event_user_id_69236c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['tenant', 'timestamp'], name='audit_event_tenant__86be43_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['category', 'timestamp'], name='audit_event_categor_59a8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['is_security_event', 'timestamp'], name='audit_event_is_secu_ab3259_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['data_subject', 'timestamp'], name='data_access_data_su_6a13f5_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['accessor', 'timestamp'], name='data_access_accesso_b5648f_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['access_type', 'timestamp'], name='data_access_access__d0ec44_idx'),
        ),
        migrations.AddIndex(
            model_name='sagastep',
            index=models.Index(fields=['saga', 'step_order'], name='saga_steps_saga_id_e96046_idx'),
        ),
        migrations.AddIndex(
            model_name='sagastep',
            index=models.Index(fields=['saga', 'status'], name='saga_steps_saga_id_3976fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sagastep',
            unique_together={('saga', 'step_name')},
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'status'], name='audit_secur_event_t_ddf278_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['risk_score'], name='audit_secur_risk_sc_54c146_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['response_required', 'status'], name='audit_secur_respons_bdc726_idx'),
        ),
        migrations.AddIndex(
            model_name='systemchangelog',
            index=models.Index(fields=['change_type', 'timestamp'], name='system_chan_change__d40298_idx'),
        ),
        migrations.AddIndex(
            model_name='systemchangelog',
            index=models.Index(fields=['component', 'timestamp'], name='system_chan_compone_b5a470_idx'),
        ),
    ]
