# Generated by Django 5.2.3 on 2026-05-31 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand_dna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_dna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='brand_dna.branddna')),
            ],
            options={
                'db_table': 'content_pipeline_calendar',
            },
        ),
        migrations.CreateModel(
            name='ContentPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('caption', models.TextField()),
                ('image_url', models.URLField(max_length=1000)),
                ('suggested_time', models.TimeField()),
                ('hashtags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='content_pipeline.contentcalendar')),
            ],
            options={
                'db_table': 'content_pipeline_post',
                'ordering': ['day_number'],
            },
        ),
    ]
