# Generated by Django 5.2.3 on 2026-06-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='user_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='user_status',
            field=models.CharField(choices=[('pending', 'Pendiente revisión'), ('approved', 'Aprobado'), ('edited', 'Editado por usuario'), ('change_requested', 'Cambio solicitado')], default='pending', max_length=20),
        ),
    ]
