# Generated by Django 5.2.3 on 2026-06-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0002_add_user_feedback_to_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='regen_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
