# Generated by Django 5.2.3 on 2026-07-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0004_weeklyfeedback_active_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
