# Generated by Django 5.2.3 on 2026-07-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0005_contentpost_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcalendar',
            name='next_week_generating',
            field=models.BooleanField(default=False),
        ),
    ]
