# Generated by Django 5.2.3 on 2026-07-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0006_contentcalendar_next_week_generating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
