# Generated by Django 5.2.3 on 2026-07-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0007_contentpost_downloaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='format',
            field=models.CharField(default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
