# Generated by Django 5.2.3 on 2026-07-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0008_contentpost_format_contentpost_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpost',
            name='format',
            field=models.CharField(choices=[('single', 'Imagen única'), ('carousel', 'Carrusel')], default='single', max_length=20),
        ),
    ]
