# Generated by Django 5.2.3 on 2026-07-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0009_alter_contentpost_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contentpost',
            name='format',
            field=models.CharField(choices=[('single', 'Imagen única'), ('carousel', 'Carrusel'), ('reel', 'Reel')], default='single', max_length=20),
        ),
    ]
