# Generated by Django 5.2.3 on 2026-07-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0011_remove_contentcalendar_active_product_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyFeedback',
        ),
    ]
