# Generated by Django 5.2.3 on 2026-07-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0012_delete_weeklyfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcalendar',
            name='last_reactivation_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
