# Generated by Django 5.2.3 on 2026-08-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0013_contentcalendar_last_reactivation_email_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='regenerating',
            field=models.BooleanField(default=False),
        ),
    ]
