# Generated by Django 5.2.3 on 2026-08-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0014_contentpost_regenerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='product_photo_background_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
