# Generated by Django 5.2.3 on 2026-08-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0015_contentpost_product_photo_background_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcalendar',
            name='first_download_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
