# Usar la misma base que la imagen principal para consistencia
FROM python:3.12-slim

# Variables de entorno para Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Crear directorio de trabajo
WORKDIR /app

# Instalar dependencias del sistema (si las hubiera, como postgresql-client)
RUN apt-get update && apt-get install -y postgresql-client ffmpeg curl unzip && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends \
    libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 \
    libdbus-1-3 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 \
    libxrandr2 libgbm1 libasound2 libpango-1.0-0 libcairo2 libatspi2.0-0 \
    libx11-6 libxcb1 libxext6 wget && \
    rm -rf /var/lib/apt/lists/*

# Copiar archivo de requerimientos e instalar dependencias de Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    python -m playwright install chromium

# Copiar TODO el código fuente al contenedor
# Este es el paso crucial que asegura que los workers siempre tengan el código
COPY . .

# El entrypoint y el comando se definen en docker-compose.yml
# para mantener la flexibilidad.
