# Generated by Django 5.2.3 on 2026-05-31 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('business_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('stage', models.CharField(choices=[('web', 'Analizando sitio web'), ('logo', 'Analizando logo'), ('posts', 'Analizando posts'), ('content', 'Generando contenido'), ('complete', 'Completo')], default='web', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('logo_file_path', models.CharField(blank=True, default='', max_length=500)),
                ('post_images_paths', models.JSONField(blank=True, default=list)),
                ('posts_text', models.TextField(blank=True, default='')),
                ('profile_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brand_dna_analysis_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandDNA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_url', models.URLField()),
                ('description', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('audience', models.TextField()),
                ('tone', models.CharField(max_length=50)),
                ('primary_colors', models.JSONField(default=list)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('logo_elements', models.TextField(blank=True, default='')),
                ('posting_style', models.TextField(blank=True, default='')),
                ('avg_caption_length', models.IntegerField(default=150)),
                ('common_hashtags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_dna', to='brand_dna.analysisjob')),
            ],
            options={
                'db_table': 'brand_dna_brand_dna',
            },
        ),
    ]
