# Generated by Django 5.2.3 on 2026-06-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_dna', '0003_analysisjob_product_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
