# Generated by Django 5.2.3 on 2026-06-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_dna', '0004_analysisjob_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='product_image_paths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
