# Generated by Django 5.2.3 on 2026-06-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_dna', '0005_product_image_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='business_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='business_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='branddna',
            name='business_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
