# Generated by Django 5.2.3 on 2026-07-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_dna', '0007_remove_analysisjob_product_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='generation_mode',
            field=models.CharField(choices=[('full', 'Calendario completo'), ('sample_image', 'Muestra: imagen'), ('sample_reel', 'Muestra: reel')], default='full', max_length=20),
        ),
    ]
