# Generated by Django 5.2.3 on 2026-07-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_dna', '0008_analysisjob_generation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddna',
            name='approved_fields',
            field=models.JSONField(default=list),
        ),
    ]
