# Generated by Django 5.2.3 on 2026-07-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_dna', '0009_branddna_approved_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='product_reference_image_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='generation_mode',
            field=models.CharField(choices=[('full', 'Calendario completo'), ('sample_image', 'Muestra: imagen'), ('sample_reel', 'Muestra: reel'), ('sample_product_image', 'Muestra: imagen con producto real (solo admin)'), ('sample_product_reel', 'Muestra: reel con producto real (solo admin)')], default='full', max_length=20),
        ),
    ]
