# Generated by Django 5.2.3 on 2026-08-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_dna', '0010_analysisjob_product_reference_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='generation_mode',
            field=models.CharField(choices=[('full', 'Calendario completo'), ('sample_image', 'Muestra: imagen'), ('sample_reel', 'Muestra: reel'), ('sample_product_reel', 'Muestra: reel con producto real (solo admin)')], default='full', max_length=20),
        ),
    ]
