# Generated by Django 5.2.3 on 2026-08-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_dna', '0011_alter_analysisjob_generation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddna',
            name='product_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branddna',
            name='product_photo_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='generation_mode',
            field=models.CharField(choices=[('full', 'Calendario completo'), ('sample_image', 'Muestra: imagen'), ('sample_reel', 'Muestra: reel')], default='full', max_length=20),
        ),
    ]
