# Generated by Django 5.2.3 on 2026-08-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_dna', '0013_productphotoprecheckattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisjob',
            name='product_reference_image_path',
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='product_reference_image_paths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
