# Generated by Django 5.2.3 on 2025-08-15 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_plan_remove_tenantmodel_plan_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_daily_interactions',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_monthly_interactions',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
