# Generated by Django 5.2.3 on 2025-08-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0003_plan_created_at_plan_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
