# Generated by Django 5.2.3 on 2025-08-20 02:26

from django.db import migrations


def seed_plans(apps, schema_editor):
    """
    Seeds the database with the initial Free and Premium plans.
    """
    Plan = apps.get_model('tenant_management', 'Plan')

    # Create Free Plan
    Plan.objects.create(
        name='Free',
        max_daily_interactions=20,
        max_monthly_interactions=500,
        price=0.00
    )

    # Create Premium Plan
    Plan.objects.create(
        name='Premium',
        max_daily_interactions=1000,
        max_monthly_interactions=30000,
        price=99.00
    )


def unseed_plans(apps, schema_editor):
    """
    Removes the initial plans from the database.
    """

    Plan = apps.get_model('tenant_management', 'Plan')
    Plan.objects.filter(name__in=['Free', 'Premium']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0005_alter_plan_price'),
    ]

    operations = [
        migrations.RunPython(seed_plans, reverse_code=unseed_plans),
    ]
