# Generated by Django 5.2.3 on 2025-08-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0006_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
