# Generated by Django 5.2.3 on 2025-08-25 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0007_user_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorInteractionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=100)),
                ('details', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_interactions', to='tenant_management.tenantmodel')),
            ],
            options={
                'verbose_name': 'Error Interaction',
                'verbose_name_plural': 'Error Interactions',
                'db_table': 'error_interaction',
                'ordering': ['-timestamp'],
            },
        ),
    ]
