# Generated by Django 5.2.3 on 2025-10-09 18:11

import core.tenant_management.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0010_loginattempt_blacklistedtoken_passwordhistory_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.tenant_management.models.UserManager()),
            ],
        ),
    ]
