# Generated by Django 5.2.3 on 2026-06-03 18:07

from django.db import migrations, models


def create_default_plans(apps, schema_editor):
    Plan = apps.get_model('tenant_management', 'Plan')
    Plan.objects.get_or_create(
        name='Free',
        defaults={
            'max_daily_interactions': 100,
            'max_monthly_interactions': 1000,
            'max_calendars_per_week': 2,
            'max_post_regenerations': 2,
            'max_post_edits': 2,
            'price': '0.00',
        },
    )
    Plan.objects.get_or_create(
        name='Admin',
        defaults={
            'max_daily_interactions': 99999,
            'max_monthly_interactions': 99999,
            'max_calendars_per_week': 99999,
            'max_post_regenerations': 99999,
            'max_post_edits': 99999,
            'price': '0.00',
        },
    )


def remove_default_plans(apps, schema_editor):
    Plan = apps.get_model('tenant_management', 'Plan')
    Plan.objects.filter(name__in=['Free', 'Admin']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_calendars_per_week',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_post_edits',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_post_regenerations',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.RunPython(create_default_plans, remove_default_plans),
    ]
