# Generated by Django 5.2.3 on 2026-07-05 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0016_user_deactivated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
