# Generated by Django 5.2.3 on 2026-07-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0019_remove_user_reels_carousel_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allows_sample_generation',
            field=models.BooleanField(default=False),
        ),
    ]
