# Generated by Django 5.2.3 on 2026-07-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0020_plan_allows_sample_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
