# Generated by Django 5.2.3 on 2026-07-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0022_subscription_stripe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
