# Generated by Django 5.2.3 on 2026-08-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0024_user_last_reactivation_email_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_photo_prechecks_per_day',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
