# Generated by Django 5.2.3 on 2026-08-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0025_plan_max_photo_prechecks_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_product_reference_photos',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
