# Generated by Django 5.2.3 on 2026-08-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0026_plan_max_product_reference_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_payment_link_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
