# Generated by Django 5.2.3 on 2026-08-24 03:32

from django.db import migrations, models


def encender_en_planes_internos(apps, schema_editor):
    Plan = apps.get_model('tenant_management', 'Plan')
    Plan.objects.filter(name__in=['Tester', 'Admin']).update(
        allows_calendar_deletion=True
    )


def apagar_en_planes_internos(apps, schema_editor):
    Plan = apps.get_model('tenant_management', 'Plan')
    Plan.objects.filter(name__in=['Tester', 'Admin']).update(
        allows_calendar_deletion=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0028_logintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allows_calendar_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(encender_en_planes_internos, apagar_en_planes_internos),
    ]
