# Generated by Django 5.2.3 on 2026-05-16 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesión del agente',
                'verbose_name_plural': 'Sesiones del agente',
                'db_table': 'agent_session',
            },
        ),
        migrations.CreateModel(
            name='AgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('model_used', models.CharField(max_length=100)),
                ('tool_used', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('estimated_tokens', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='agent.agentsession')),
            ],
            options={
                'verbose_name': 'Solicitud al agente',
                'verbose_name_plural': 'Solicitudes al agente',
                'db_table': 'agent_request',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agent.agentsession')),
            ],
            options={
                'verbose_name': 'Memoria del agente',
                'verbose_name_plural': 'Memorias del agente',
                'db_table': 'agent_memory',
                'ordering': ['timestamp'],
            },
        ),
    ]
