# Generated by Django 5.2.3 on 2026-05-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X')], max_length=50)),
                ('username', models.CharField(max_length=255)),
                ('cookies', models.JSONField(default=list)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesión de navegador',
                'verbose_name_plural': 'Sesiones de navegador',
                'db_table': 'agent_browser_session',
                'unique_together': {('platform', 'username')},
            },
        ),
    ]
