# Generated by Django 5.2.3 on 2026-05-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_pendingjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255)),
                ('chat_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews_total', models.IntegerField(default=0)),
                ('giro', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('score_reason', models.CharField(blank=True, max_length=255)),
                ('contacted', models.BooleanField(default=False)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-searched_at', '-score'],
                'unique_together': {('place_id', 'chat_id')},
            },
        ),
    ]
