# Generated by Django 5.2.3 on 2026-05-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_prospectlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
